#!/usr/bin/env bash
# Builds the map assets that are bundled into the APK:
#   app/src/main/assets/style.json          (generated by gen-style.mjs)
#   app/src/main/assets/vector_layers.json  (generated by gen-style.mjs from the planet metadata,
#                                            with a built-in fallback list when offline)
#   app/src/main/assets/sprites/v4/dark*    (Protomaps dark sprites, 1x and 2x)
#   app/src/main/assets/fonts/<stack>/*.pbf (all 256 glyph ranges of Noto Sans Regular/Medium/Italic)
#   app/src/main/assets/fonts/OFL.txt       (font licence)
#
# Files that already exist are not downloaded again, so re-runs are cheap.
# Requires: node + npm, curl, xargs. Run from anywhere: it cd's into its own directory.
# Environment: VELOTRACK_LANG (label language, default en), PARALLEL (downloads, default 16).
set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$TOOLS_DIR"

ASSETS_DIR="$(cd "$TOOLS_DIR/.." && pwd)/app/src/main/assets"
BASE_URL="https://raw.githubusercontent.com/protomaps/basemaps-assets/main"
PARALLEL="${PARALLEL:-16}"
STACKS=("Noto Sans Regular" "Noto Sans Medium" "Noto Sans Italic")
SPRITES=(dark.json dark.png dark@2x.json dark@2x.png)

echo "==> Installing @protomaps/basemaps (tools/package.json)"
npm install --no-audit --no-fund

echo "==> Generating style.json and vector_layers.json"
mkdir -p "$ASSETS_DIR"
node gen-style.mjs "$ASSETS_DIR/style.json"   # also writes vector_layers.json next to it

# Remove partial downloads left over from an interrupted run.
if [ -d "$ASSETS_DIR/fonts" ] || [ -d "$ASSETS_DIR/sprites" ]; then
  find "$ASSETS_DIR/fonts" "$ASSETS_DIR/sprites" -name '*.part' -type f -delete 2>/dev/null || true
fi

# Download list: one "<url><TAB><dest>" line per missing file (kept next to this script so no
# temp directory is needed; removed on exit).
LIST="$TOOLS_DIR/.downloads.tmp"
: > "$LIST"
trap 'rm -f "$LIST"' EXIT

add() { # add <url> <dest>
  if [ -s "$2" ]; then
    return 0
  fi
  mkdir -p "$(dirname "$2")"
  printf '%s\t%s\n' "$1" "$2" >> "$LIST"
}

for f in "${SPRITES[@]}"; do
  add "$BASE_URL/sprites/v4/$f" "$ASSETS_DIR/sprites/v4/$f"
done
add "$BASE_URL/fonts/OFL.txt" "$ASSETS_DIR/fonts/OFL.txt"

for stack in "${STACKS[@]}"; do
  enc="${stack// /%20}"
  start=0
  while [ "$start" -le 65280 ]; do
    range="${start}-$((start + 255))"
    add "$BASE_URL/fonts/$enc/$range.pbf" "$ASSETS_DIR/fonts/$stack/$range.pbf"
    start=$((start + 256))
  done
done

COUNT="$(wc -l < "$LIST" | tr -d ' ')"
if [ "$COUNT" -gt 0 ]; then
  echo "==> Downloading $COUNT files from $BASE_URL ($PARALLEL in parallel)"
  # NUL-separated lines keep paths with spaces intact; each line is split on the tab inside bash -c.
  tr '\n' '\0' < "$LIST" | xargs -0 -P "$PARALLEL" -n 1 bash -c '
    set -euo pipefail
    tab="$(printf "\t")"
    line="$1"
    url="${line%%"$tab"*}"
    dest="${line#*"$tab"}"
    curl -fsSL --retry 3 --retry-delay 2 --retry-all-errors -o "$dest.part" "$url"
    mv -f "$dest.part" "$dest"
  ' _
else
  echo "==> All sprite and glyph files already present"
fi

echo "==> Verifying"
for stack in "${STACKS[@]}"; do
  n="$(find "$ASSETS_DIR/fonts/$stack" -name '*.pbf' -type f | wc -l | tr -d ' ')"
  if [ "$n" -ne 256 ]; then
    echo "error: '$stack' has $n glyph files, expected 256" >&2
    exit 1
  fi
done
for f in "${SPRITES[@]}" ; do
  if [ ! -s "$ASSETS_DIR/sprites/v4/$f" ]; then
    echo "error: missing sprite file sprites/v4/$f" >&2
    exit 1
  fi
done
for f in "$ASSETS_DIR/fonts/OFL.txt" "$ASSETS_DIR/style.json" "$ASSETS_DIR/vector_layers.json"; do
  if [ ! -s "$f" ]; then
    echo "error: missing $f" >&2
    exit 1
  fi
done

du -sh "$ASSETS_DIR/fonts" "$ASSETS_DIR/sprites" "$ASSETS_DIR/style.json" "$ASSETS_DIR/vector_layers.json"
echo "==> Assets ready in $ASSETS_DIR"
