#!/usr/bin/env python3
"""Turn the Xcode project generated by Apple's safari-web-extension-converter into Bouclier's
App Store project. Runs on the Mac (it uses plutil), called by build.sh after the converter.

usage: xcode_setup.py <folder the converter wrote the project to> [--png-icon]

What it changes, all inside the generated project (the repo is never touched):
  1. the app's window: appstore/app/{Main.html,Style.css,Script.js,Icon.png} replace the
     template's page, after checking the template's Swift still calls show() and listens for
     "open-preferences" (the contract the page relies on);
  2. the app icon: appstore/AppIcon.icon (Icon Composer, rounded and lit by iOS / macOS 26)
     replaces the template's AppIcon.appiconset; --png-icon fills the appiconset with the flat
     full-bleed PNGs from design/appicon-fullbleed instead;
  3. Info.plist: no custom encryption (skips the export compliance question on every upload),
     display name "Bouclier", Mac App Store category Utilities;
  4. entitlements: checks both Mac targets are sandboxed (the Mac App Store requires it);
  5. rules: site-limited rules use the older "domains" keys, which every Safari from 15 to 27
     applies (see safari_domains);
  6. the template's Swift: the iPhone window scrolls (the page is taller than a 4.7-inch screen),
     links open in Safari instead of replacing the window, and from iOS 26.2 its button opens
     Bouclier's switch in Settings directly (see patch_swift).
Build settings (versions, deployment targets, team) are passed to xcodebuild by build.sh.
"""
import json
import re
import plistlib
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
APP_PAGE = REPO / "appstore" / "app"
ICON = REPO / "appstore" / "AppIcon.icon"
PNG_ICONS = REPO / "design" / "appicon-fullbleed"


def say(msg):
    print(f"  · {msg}")


def find_one(root, pattern, must=True):
    hits = sorted(root.rglob(pattern))
    hits = [h for h in hits if "DerivedData" not in h.parts]
    if not hits and must:
        sys.exit(f"xcode_setup: {pattern} not found under {root}")
    return hits


def replace_app_page(root):
    swift = "\n".join(p.read_text(errors="ignore") for p in find_one(root, "*.swift"))
    if "show(" not in swift or "open-preferences" not in swift:
        say("the template's Swift no longer calls show() / 'open-preferences': kept Apple's page")
        return
    main = [p for p in find_one(root, "Main.html") if "App" in str(p)]
    if not main:
        say("no app Main.html found: kept Apple's page")
        return
    for page in main:
        shutil.copyfile(APP_PAGE / "Main.html", page)
        resources = page.parent.parent if page.parent.name.endswith(".lproj") else page.parent
        for name in ("Style.css", "Script.js", "Icon.png"):
            shutil.copyfile(APP_PAGE / name, resources / name)
        say(f"app window replaced in {page.relative_to(root)}")


def new_id(objects):
    while True:
        oid = uuid.uuid4().hex[:24].upper()
        if oid not in objects:
            return oid


def load_pbx(pbx):
    if not pbx.read_bytes().lstrip().startswith(b"<?xml"):
        subprocess.run(["plutil", "-convert", "xml1", str(pbx)], check=True)  # OpenStep -> XML, which Xcode reads too
    with open(pbx, "rb") as f:
        return plistlib.load(f)


def install_icon(root, pbx, png_icon):
    appiconsets = [p for p in find_one(root, "AppIcon.appiconset") if "App" in str(p)]
    if png_icon:
        for iconset in appiconsets:
            fill_png_iconset(iconset)
        return
    data = load_pbx(pbx)
    objects = data["objects"]
    apps = [k for k, v in objects.items()
            if v.get("isa") == "PBXNativeTarget" and v.get("productType") == "com.apple.product-type.application"]
    # the icon goes next to the app's shared asset catalog
    catalog = next((p for p in find_one(root, "Assets.xcassets") if "Shared (App)" in str(p)), None) \
        or find_one(root, "Assets.xcassets")[0]
    folder = catalog.parent
    dest = folder / "AppIcon.icon"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(ICON, dest)
    for iconset in appiconsets:  # an .appiconset with the same name would win or clash
        parked = root / "_unused" / iconset.parent.parent.name
        parked.mkdir(parents=True, exist_ok=True)
        shutil.move(str(iconset), str(parked / iconset.name))
    synced = any(v.get("isa") == "PBXFileSystemSynchronizedRootGroup" and folder.name in (v.get("path"), v.get("name"))
                 for v in objects.values())
    if synced:
        say(f"AppIcon.icon copied into the synchronized folder {folder.name}")
    else:
        group = next((k for k, v in objects.items() if v.get("isa") == "PBXGroup"
                      and folder.name in (v.get("path"), v.get("name"))), None)
        if not group:
            sys.exit(f"xcode_setup: no group named {folder.name} in the project")
        ref = new_id(objects)
        objects[ref] = {"isa": "PBXFileReference", "lastKnownFileType": "folder.iconcomposer.icon",
                        "path": "AppIcon.icon", "sourceTree": "<group>"}
        objects[group]["children"].append(ref)
        for target in apps:
            phase = next((p for p in objects[target]["buildPhases"] if objects[p].get("isa") == "PBXResourcesBuildPhase"), None)
            if not phase:
                continue
            build_file = new_id(objects)
            objects[build_file] = {"isa": "PBXBuildFile", "fileRef": ref}
            objects[phase]["files"].append(build_file)
        say(f"AppIcon.icon added to {len(apps)} app targets")
    # every app target uses the icon named AppIcon
    for v in objects.values():
        if v.get("isa") == "XCBuildConfiguration" and "ASSETCATALOG_COMPILER_APPICON_NAME" in v.get("buildSettings", {}):
            v["buildSettings"]["ASSETCATALOG_COMPILER_APPICON_NAME"] = "AppIcon"
    with open(pbx, "wb") as f:
        plistlib.dump(data, f)


def fill_png_iconset(iconset):
    for old in iconset.glob("*.png"):
        old.unlink()
    images = [{"idiom": "universal", "platform": "ios", "size": "1024x1024", "filename": "icon_ios_1024.png"}]
    shutil.copyfile(PNG_ICONS / "icon_1024.png", iconset / "icon_ios_1024.png")
    for points, scale in [(16, 1), (16, 2), (32, 1), (32, 2), (128, 1), (128, 2), (256, 1), (256, 2), (512, 1), (512, 2)]:
        name = f"icon_{points}x{points}{'@2x' if scale == 2 else ''}.png"
        shutil.copyfile(PNG_ICONS / f"icon_{points * scale}.png", iconset / name)
        images.append({"idiom": "mac", "scale": f"{scale}x", "size": f"{points}x{points}", "filename": name})
    (iconset / "Contents.json").write_text(json.dumps({"images": images, "info": {"author": "xcode", "version": 1}}, indent=2))
    say(f"PNG icons written to {iconset.name}")


def edit_plists(root):
    for path in find_one(root, "Info.plist"):
        if "_unused" in path.parts:
            continue
        with open(path, "rb") as f:
            info = plistlib.load(f)
        is_extension = "NSExtension" in info
        info["CFBundleDisplayName"] = "Bouclier"
        # English by default, French on a device set to French: the app window (and WKWebView's
        # navigator.language) follows the language the system picks from this list
        info["CFBundleDevelopmentRegion"] = "en"
        info["CFBundleLocalizations"] = ["en", "fr"]
        if not is_extension:
            info["ITSAppUsesNonExemptEncryption"] = False
            if "macOS" in str(path):
                info["LSApplicationCategoryType"] = "public.app-category.utilities"
        with open(path, "wb") as f:
            plistlib.dump(info, f)
        say(f"{path.relative_to(root)}: {'extension' if is_extension else 'app'} keys set")


MAC_WINDOW = (500, 620)   # the app page in French needs about 593 points at this width (425 x 325 in Apple's template)


def size_mac_window(root):
    """Apple's template opens the Mac app in a 425 x 325 window that cannot be resized, so the page's
    button ("Quit and Open Safari Settings…") sat below the fold, and further down in French."""
    for board in find_one(root, "Main.storyboard", must=False):
        if "macOS" not in str(board):
            continue
        text = board.read_text()
        w, h = MAC_WINDOW
        new, n = re.subn(r'(<rect key="(?:contentRect|frame)" x="[^"]*" y="[^"]*") width="425" height="325"/>',
                         rf'\1 width="{w}" height="{h}"/>', text)
        if n:
            board.write_text(new)
            say(f"{board.relative_to(root)}: Mac window {w} x {h} ({n} frames)")
        elif f'width="{w}" height="{h}"' in text:
            say(f"{board.relative_to(root)}: Mac window already {w} x {h}")
        else:
            say(f"{board.relative_to(root)}: template changed, Mac window size left as is")


def check_sandbox(root):
    for ent in find_one(root, "*.entitlements", must=False):
        with open(ent, "rb") as f:
            data = plistlib.load(f)
        if "macOS" in str(ent) and not data.get("com.apple.security.app-sandbox"):
            data["com.apple.security.app-sandbox"] = True
            with open(ent, "wb") as f:
                plistlib.dump(data, f)
            say(f"{ent.name}: App Sandbox turned on")
        else:
            say(f"{ent.name}: sandbox {'on' if data.get('com.apple.security.app-sandbox') else 'n/a (iOS)'}")


def safari_domains(root):
    """Two Safari limits, one fix. Safari applies an allow rule's initiatorDomains nowhere, so "allow
    gpt.js on these 37 sites" became "allow gpt.js everywhere" (tested 2026-09-23, Safari on macOS 27:
    Google's gpt.js and adsbygoogle.js, Tag Manager, Criteo and Taboola all loaded on example.com).
    And Safari before 26 does not know initiatorDomains / excludedInitiatorDomains at all, so a block
    rule limited to some sites would apply everywhere, and its exceptions nowhere. The older
    "domains" / "excludedDomains" keys work in every Safari from 15 to 27, for allow and block rules
    alike (checked with tests/webkit-bench on 2026-09-28). Only the copy inside the Xcode project
    changes: Chromium, used by the tests, keeps the standard keys."""
    renamed = 0
    for path in find_one(root, "*.json", must=False):
        if path.parent.name != "rules" or "Extension" not in str(path):
            continue
        rules = json.loads(path.read_text())
        changed = False
        for r in rules:
            c = r.get("condition", {})
            for old, new in (("initiatorDomains", "domains"), ("excludedInitiatorDomains", "excludedDomains")):
                if old in c:
                    c[new] = c.pop(old)
                    renamed += 1
                    changed = True
        if changed:
            path.write_text(json.dumps(rules, separators=(",", ":")))
    say(f"site-limited rules rewritten for every Safari version: {renamed}")
    if not renamed:
        sys.exit("xcode_setup: no rules found to rewrite (did the converter copy extension/rules?)")


def patch_swift(root):
    """Small changes to the template's ViewController.swift. Each one is skipped, with a notice, when
    Apple's template no longer has the line it expects, so a new Xcode never breaks the build."""
    paths = [p for p in find_one(root, "ViewController.swift", must=False) if "App" in str(p)]
    if not paths:
        say("no ViewController.swift: Swift left as generated")
        return
    for path in paths:
        text = path.read_text()
        edits = [
            # iOS: SFSafariSettings lives in SafariServices
            ("#if os(iOS)\nimport UIKit\n", "#if os(iOS)\nimport UIKit\nimport SafariServices\n", "import SafariServices on iOS"),
            # the page is taller than an iPhone 8 / SE screen: let it scroll instead of cutting the end off
            ("self.webView.scrollView.isScrollEnabled = false", "self.webView.scrollView.isScrollEnabled = true", "scrolling on iPhone"),
            # iOS 26.2+: tell the page that its button can open Bouclier's switch in Settings
            ('        webView.evaluateJavaScript("show(\'ios\')")\n',
             '        if #available(iOS 26.2, *) {\n'
             '            webView.evaluateJavaScript("show(\'ios\', undefined, true, true)")\n'
             '        } else {\n'
             '            webView.evaluateJavaScript("show(\'ios\')")\n'
             '        }\n', "iOS page told about the Settings button"),
            # a link (the ad-block test, or "abuse.ch" that iOS turns into one) opens in Safari, never inside the app window
            ("    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {\n",
             "    func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void) {\n"
             "        if let url = navigationAction.request.url, !url.isFileURL, url.scheme != \"about\" {\n"
             "#if os(iOS)\n"
             "            UIApplication.shared.open(url)\n"
             "#elseif os(macOS)\n"
             "            // Safari, not the default browser: the test link only means something where Bouclier runs\n"
             "            if let safari = NSWorkspace.shared.urlForApplication(withBundleIdentifier: \"com.apple.Safari\") {\n"
             "                NSWorkspace.shared.open([url], withApplicationAt: safari, configuration: NSWorkspace.OpenConfiguration())\n"
             "            } else {\n"
             "                NSWorkspace.shared.open(url)\n"
             "            }\n"
             "#endif\n"
             "            decisionHandler(.cancel)\n"
             "            return\n"
             "        }\n"
             "        decisionHandler(.allow)\n"
             "    }\n\n"
             "    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {\n",
             "links open in Safari"),
            # iOS 26.2+: the button opens Settings > Apps > Safari > Extensions > Bouclier
            ("    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {\n",
             "    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {\n"
             "#if os(iOS)\n"
             "        if #available(iOS 26.2, *) {\n"
             "            if (message.body as? String) == \"open-preferences\" {\n"
             "                SFSafariSettings.openExtensionsSettings(forIdentifiers: [extensionBundleIdentifier]) { _ in }\n"
             "            }\n"
             "        }\n"
             "#endif\n", "iOS Settings button"),
        ]
        for old, new, what in edits:
            if old in text and new not in text:
                text = text.replace(old, new, 1)
                say(f"{path.name}: {what}")
            elif new not in text:
                say(f"{path.name}: template changed, skipped: {what}")
        path.write_text(text)


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    root = Path(sys.argv[1]).resolve()
    png_icon = "--png-icon" in sys.argv
    pbx = find_one(root, "project.pbxproj")[0]
    print(f"Preparing {pbx.parent.parent.name} for the App Store")
    replace_app_page(root)
    patch_swift(root)
    install_icon(root, pbx, png_icon)
    edit_plists(root)
    size_mac_window(root)
    check_sandbox(root)
    safari_domains(root)


if __name__ == "__main__":
    main()
